import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { config, dom } from "@fortawesome/fontawesome-svg-core";
import Header from "../src/components/generic/Header";
import Separator from "../src/components/generic/Separator";
import Waitlist from "../src/components/landing/Waitlist";
import FeatureGrid from "../src/components/landing/FeatureGrid";
import FeatureSection from "../src/components/landing/FeatureSection";
import FAQ from "../src/components/landing/FAQ";
import CTA from "../src/components/landing/CTA";
import Footer from "../src/components/generic/Footer";
import AOS from "aos";
import "aos/dist/aos.css";

export default function Home() {
	useEffect(() => {
		AOS.init({
			offset: 200,
			duration: 750,
		});
	}, []);

	return (
		<div>
			<Head>
				<title>Lorem Ipsum</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<style>{dom.css()}</style>
			</Head>
			<main className="bg-white">
				<Header />
				<div
					data-aos="fade-up"
					className="px-4 bg-gradient-to-b from-white to-primary"
				>
					<div className="text-center max-w-2xl m-auto pt-40">
						<h1 className="text-7xl font-bold text-midnight-blue mb-16">
							Lorem ipsum dolor sit amet
							<span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-primary">
								{` copilot`}
							</span>
						</h1>
						<p className="text-2xl font-medium text-gray-600 my-8">
							Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
							nisi ut aliquip ex ea commodo consequat.
						</p>
						<Waitlist />
					</div>
					<div className="max-w-6xl h-96 bg-midnight-blue m-auto mt-20 rounded-t-lg"></div>
					<div className="max-w-6xl h-96 bg-midnight-blue m-auto mb-20 rounded-b-lg"></div>
					<div className="m-auto max-w-2xl py-16" data-aos="fade-up">
						<h2 className="text-white text-4xl font-bold mt-4 text-center">
							Duis aute irure dolor in reprehenderit in voluptate velit
						</h2>
						<p className="text-center text-2xl font-medium my-8 text-white">
							esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
							occaecat cupidatat non proident
						</p>
					</div>
				</div>
				<div className="bg-white py-16" data-aos="fade-up">
					<div className="m-auto max-w-2xl my-16">
						<h2 className="text-midnight-blue text-4xl font-bold mt-4 text-center">
							Sunt in culpa qui officia deserunt mollit anim id est laborum
						</h2>
						<p className="text-center text-2xl font-medium my-8 text-gray-600">
							Sed ut perspiciatis unde omnis iste natus error sit voluptatem
							accusantium doloremque laudantium, totam rem aperiam
						</p>
					</div>
				</div>
				<div className="px-2 overflow-hidden">
					<FeatureSection
						title="Neque porro quisquam est, qui dolorem ipsum"
						subtitle="Quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora"
						quote="Incidunt ut labore et dolore magnam aliquam"
						name="Leonardo Da Vinci"
						side="left"
					/>
				</div>
				<div className="mt-16 px-2">
					<FeatureSection
						title="Et quasi architecto beatae vitae dicta sunt explicabo"
						subtitle="Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit."
						quote="Sed quia consequuntur magni dolores eos qui ratione."
						name="Napoleon Bonaparte"
						side="right"
					/>
				</div>
				<div className="my-16 px-2" data-aos="fade-up">
					<FAQ />
				</div>
				<div className="my-16 px-2" data-aos="fade-up">
					<CTA
						title="Ut enim ad minima veniam, quis nostrum exercitationem"
						subtitle="ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur"
					/>
				</div>
				<Footer />
			</main>
		</div>
	);
}

// 1. Recommendations
// 2. Accessibility

// Another idea: Increase your digital footprint
